name: photoschool
description: 웅진씽크빅 인턴과제

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # icon 라이브러리
  cupertino_icons: ^1.0.3

  # 카메라, 사진 호출
  image_picker: ^0.8.1+3
  # 사진 압축
  flutter_native_image: ^0.0.6
  # svg 이미지 사용
  flutter_svg: ^0.22.0
  # 이미지 캐싱 사용
  cached_network_image: ^3.0.0

  # 환경변수 dotenv 사용
  flutter_dotenv: ^5.0.0

  # http 및 xml 파싱
  http: 0.13.3
  xml_parser: 1.0.0
  flutter_html: ^2.1.0

  # 런처 아이콘
  flutter_launcher_icons: ^0.9.0

  # 내부 기기에 특정 값을 저장
  shared_preferences: ^2.0.6

  # Google 로그인
  google_sign_in: ^5.0.4

  # firebase
  firebase_core: ^1.3.0
  firebase_storage: ^9.0.0
  firebase_auth: ^2.0.0
  firebase_messaging: ^10.0.3

  # dart linter
  effective_dart: ^1.3.2

  # windows
  firedart: ^0.9.0+1
  hive: ^2.0.4

  # google maps
  google_maps_flutter: ^2.0.6

  # datetime format
  intl: ^0.17.0

  # scroll_refresh
  pull_to_refresh: ^2.0.0

  # lottie 애니메이션
  lottie: ^1.1.0

  # getX
  get: ^4.1.4

  # notification
  flutter_local_notifications: ^6.0.0

  # webview
  flutter_inappwebview: ^5.3.2
  url_launcher: ^6.0.0-nullsafety.4

  # painter
  painter: ^2.0.0
  flutter_colorpicker: ^0.4.0
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.3

flutter:
  uses-material-design: true
  fonts:
    - family: SDChild
      fonts:
        - asset: fonts/SDChildfundkoreaTTF.ttf
    - family: SDSamlip
      fonts:
        - asset: fonts/SDSamliphopangcheTTFOutline.ttf
    - family: KCCDodam
      fonts:
        - asset: fonts/KCCDodamdodam.ttf
    - family: DdoDdo
      fonts:
        - asset: fonts/또또사랑 OTF Medium.otf
        - asset: fonts/또또사랑 OTF Bold.otf
          weight: 700
  assets:
    - assets/
    - dotenv

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
